const cars = [
   {
      "id": 1,
      "image1": 'img/car1.jpg',
      "name":'Tesla S',
      "stamps": 'tesla',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '500-1000',
      "price": {
         "day": 750,
      },
      "power": '',
      "color": 'black',
   },
   {
      "id": 2,
      "image1": 'img/car2.jpg',
      "name":'Tesla X Plaid',
      "stamps": 'tesla',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '1000-1500',
      "price": {
         "day": 1.554,
      },
      "color": 'gray',
   },
   {
      "id": 3,
      "image1": 'img/car3.jpg',
      "name":'Tesla Model 3',
      "stamps": 'tesla',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '200-500',
      "price": {
         "day": 489,
      },
      "color": 'white',
   },
   {
      "id": 4,
      "image1": 'img/car4.jpg',
      "name":'Mercedes Gelandewagen',
      "stamps": 'mercedes',
      "type": 'SUV',
      "new":'',
      "priceFilter": '500-1000',
      "price": {
         "day": 889,
      },
      "color": 'black',
   },
   {
      "id": 5,
      "image1": 'img/car5.jpg',
      "name":'Land Cruiser 300',
      "stamps": 'toyota',
      "type": 'SUV',
      "new":'new',
      "priceFilter": '200-500',
      "price": {
         "day": 258,
      },
      "color": 'white',
   },
   {
      "id": 6,
      "image1": 'img/car6.jpg',
      "name":'Mercedes S-class',
      "stamps": 'mercedes',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '200-500',
      "price": {
         "day": 481,
      },
      "color": 'gray',
   },
   {
      "id": 7,
      "image1": 'img/car7.jpg',
      "name":'Toyota Camry',
      "stamps": 'toyota',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '200-500',
      "price": {
         "day": 367,
      },
      "color": 'black',
   },
   {
      "id": 8,
      "image1": 'img/car8.jpg',
      "name":'Range Rover',
      "stamps": 'land rover',
      "type": 'SUV',
      "new":'new',
      "priceFilter": '500-1000',
      "price": {
         "day": 592,
      },
      "color": 'gray',
   },
   {
      "id": 9,
      "image1": 'img/car9.jpg',
      "name":'Chevrolet Tahoe',
      "stamps": 'chevrolet',
      "type": 'SUV',
      "new":'new',
      "priceFilter": '200-500',
      "price": {
         "day": 370,
      },
      "color": 'white',
   },
   {
      "id": 10,
      "image1": 'img/car10.jpg',
      "name":'Kia K5',
      "stamps": 'kia',
      "type": 'sedan',
      "new":'new',
      "price": {
         "day": 52,
      },
      "color": 'gray',
   },
   {
      "id": 11,
      "image1": 'img/car11.jpg',
      "name":'Lamborghini Huracan',
      "stamps": 'lamborghini',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '1000-1500',
      "price": {
         "day": '1.000',
      },
      "color": 'gray',
   },
   {
      "id": 12,
      "image1": 'img/car12.jpg',
      "name":'Cadillac Escalade',
      "stamps": 'cadillac',
      "type": 'SUV',
      "new":'new',
      "priceFilter": '500-1000',
      "price": {
         "day": 815,
      },
      "color": 'black',
   },
   {
      "id": 13,
      "image1": 'img/car13.jpg',
      "name":'GMC Yukon',
      "stamps": 'GMC',
      "type": 'SUV',
      "new":'new',
      "priceFilter": '200-500',
      "price": {
         "day": 402,
      },
      "color": 'black',
   },
   {
      "id": 14,
      "image1": 'img/car14.jpg',
      "name":'Rolls Royce Wraith',
      "stamps": 'rolls royce',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '1000-1500',
      "price": {
         "day": 1.359,
      },
      "color": 'black',
   },
   {
      "id": 15,
      "image1": 'img/car15.jpg',
      "name":'Rolls Royce Cullinan',
      "stamps": 'rolls royce',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '1000-1500',
      "price": {
         "day": 1.481,
      },
      "color": 'gray',
   },
   {
      "id": 16,
      "image1": 'img/car16.jpg',
      "name":'Lexus ES',
      "stamps": 'lexus',
      "type": 'sedan',
      "new":'new',
      "priceFilter": '500-1000',
      "price": {
         "day": 734,
      },
      "color": 'white',
   },
   {
      "id": 17,
      "image1": 'img/car17.jpg',
      "name":'Lamborghini Urus',
      "stamps": 'lamborghini',
      "type": 'SUV',
      "new":'new',
      "priceFilter": '1000-1500',
      "price": {
         "day": 1.073,
      },
      "color": 'gray',
   },
]

